name: multiplatform_widgets
description: Simple multiplatform widgets.
version: 0.5.0
author: Denis Filonov
homepage: https://filonov.pro

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_list_tile: ^0.1.4
  cupertino_radio_choice: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
